name: CD Pipeline

# Only trigger, when the ci workflow succeeded
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Docker image
      run: sudo docker pull eggboixd/module1-cicd:latest
    - name: Delete old container
      run: docker rm -f module1-cicd || true
    - name: Remove old Docker image
      run: docker rmi eggboixd/module1-cicd:latest || true
    - name: Run Docker container
      run: docker run -d --name module1-cicd -p 8080:8080 eggboixd/module1-cicd:latest
